name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update gradle wrapper
        run: ./gradlew wrapper --gradle-version 6.2.1
      - name: Sign Archives
        run: ./gradlew assemble -x signArchives
        env:
          signingKey: ${{ secrets.signingKey }}
          signingPassword: ${{ secrets.signingPassword }}
      - name: Build with Gradle
        run: gradle release
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}



#    - name: Publish to GitHub Packages
#      run: ./gradlew unSnapshotVersion && ./gradlew publish
#      env:
#        USERNAME: ${{ github.actor }}
#        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
